{{- if .Values.secrets }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  namespace: {{ .Values.global.namespace | default .Values.namespace }}-{{ .Values.global.env | default .Values.env }}
  name: {{ include "helm-common.fullname" . }}-secrets
spec:
  itemPath: "vaults/{{ .Values.global.env | default .Values.env | title }} {{ .Values.onepassword.vault }}/items/{{ tpl .Values.secrets.name $ }}"
{{- end }}