{{- if eq .Values.deployment.type "deployment" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helm-common.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "helm-common.fullname" . }}
{{- end }}