{{- if .Values.service.create -}}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace | default .Values.namespace }}-{{ .Values.global.env | default .Values.env }}
  name: {{ include "helm-common.fullname" . }}
  labels:
    {{- include "helm-common.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "helm-common.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}