name: 'Configure an EKS cluster on AWS'

on:
  push:
    branches:
    - eks/**
    paths:
      - 'config/**'
  pull_request:
    branches:
    - eks/**
    paths:
      - 'config/**'

jobs:
  terraform_apply:
    name: 'Configure EKS with terraform'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      WORKDIR: tf/Configure/AWS
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: DS/Kubernetes
        token: ${{ secrets.GIT_TOKEN }}
        fetch-depth: 0
        ref: main
        path: tf

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: v1.3.0

    - name: Set region and cluster name on pull_request
      if: github.event_name == 'pull_request'
      run: |
        echo "TF_VAR_region=$(echo ${{ github.base_ref }} | cut -d / -f 2)" >> $GITHUB_ENV
        echo "TF_VAR_cluster_name=$(echo ${{ github.base_ref }} | cut -d / -f 3)" >> $GITHUB_ENV

    - name: Set region and cluster name on push
      if: github.event_name == 'push'
      run: |
        echo "TF_VAR_region=$(echo ${GITHUB_REF##*eks/} | cut -d / -f 1)" >> $GITHUB_ENV
        echo "TF_VAR_cluster_name=$(echo ${GITHUB_REF##*eks/} | cut -d / -f 2)" >> $GITHUB_ENV

    - name: Working environment
      run: |
        echo "# Deploying EKS cluster"  >> $GITHUB_STEP_SUMMARY
        echo "## Environment:"  >> $GITHUB_STEP_SUMMARY
        echo "- AWS region: ${{ env.TF_VAR_region }}" >> $GITHUB_STEP_SUMMARY
        echo "- EKS cluster: ${{ env.TF_VAR_cluster_name }}" >> $GITHUB_STEP_SUMMARY

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.TF_VAR_region }}

    - name: Copy config files
      run: |
        cp config/* ${{ env.WORKDIR }}/.

    - name: Terraform Init
      working-directory: ${{ env.WORKDIR }}
      run: |
        echo "## Terraform Init" >> $GITHUB_STEP_SUMMARY
        echo "***terraform init -backend-config 'key=eks-config/${{ env.TF_VAR_region }}-${{ env.TF_VAR_cluster_name }}/terraform.tfstate'***" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        terraform init -backend-config 'key=eks-config/${{ env.TF_VAR_region }}-${{ env.TF_VAR_cluster_name }}/terraform.tfstate' -no-color  >> $GITHUB_STEP_SUMMARY 2>&1
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Terraform Plan
      working-directory: ${{ env.WORKDIR }}
      if: github.event_name == 'pull_request'
      run: |
        echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
        echo "***terraform plan***" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        terraform plan -no-color  >> $GITHUB_STEP_SUMMARY 2>&1
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Terraform Apply
      working-directory: ${{ env.WORKDIR }}
      if: github.event_name == 'push'
      run: |
        echo "## Terraform Apply" >> $GITHUB_STEP_SUMMARY
        echo "***terraform apply -auto-approve***" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        terraform apply -auto-approve -no-color  >> $GITHUB_STEP_SUMMARY 2>&1
        echo '```' >> $GITHUB_STEP_SUMMARY